# Generated by Django 3.1.7 on 2021-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210307_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approvedby',
            field=models.IntegerField(null=True),
        ),
    ]
