# Generated by Django 3.1.7 on 2021-03-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_logindetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Android', 'Android')], max_length=100)),
                ('ticket_type', models.CharField(choices=[('New devlopment', 'New devlopment'), ('Update', 'Update'), ('Bug', 'Bug')], max_length=100)),
                ('question', models.CharField(max_length=250)),
                ('desc', models.TextField(null=True)),
                ('trd', models.DateTimeField(null=True)),
                ('tod', models.DateTimeField(null=True)),
                ('tcd', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
