# Generated by Django 3.1.7 on 2021-03-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20210322_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat',
            new_name='category',
        ),
    ]
